import { useMemo, useState } from 'react';
import { KNOWLEDGE_GUIDE_EXTRA_ARTICLES } from '../../../components/knowledgeGuideExtraArticles';
import { KNOWLEDGE_GUIDE_MORE_ARTICLES } from '../../../components/knowledgeGuideMoreArticles';
import { KNOWLEDGE_GUIDE_FIELD_ARTICLES } from '../../../components/knowledgeGuideFieldArticles';
import { KNOWLEDGE_GUIDE_SOIL_HEALTH_ARTICLES } from '../../../components/knowledgeGuideSoilHealthArticles';
import { knowledgeSources } from '../data/sources.ts';
import { knowledgeEntries } from '../services/catalog.ts';
import './KnowledgeLibrary.css';

type Article={id:string;category:string;title:string;summary:string;tags:string[];sections:Array<{title:string;text:string}>};
const ARTICLES:Article[]=[...KNOWLEDGE_GUIDE_EXTRA_ARTICLES,...KNOWLEDGE_GUIDE_MORE_ARTICLES,...KNOWLEDGE_GUIDE_FIELD_ARTICLES,...KNOWLEDGE_GUIDE_SOIL_HEALTH_ARTICLES];
const categories=[...new Set(ARTICLES.map(a=>a.category))].sort((a,b)=>a.localeCompare(b,'tr'));
export default function KnowledgeLibrary(){
 const[query,setQuery]=useState('');const[category,setCategory]=useState('Tümü');const[selectedId,setSelectedId]=useState<string|null>(null);
 const articles=useMemo(()=>{const n=query.trim().toLocaleLowerCase('tr-TR');return ARTICLES.filter(a=>(category==='Tümü'||a.category===category)&&(!n||[a.title,a.summary,a.category,...a.tags].join(' ').toLocaleLowerCase('tr-TR').includes(n)))},[query,category]);
 const selected=ARTICLES.find(a=>a.id===selectedId);const labels=knowledgeEntries.filter(e=>e.contentType==='label');
 return <section className="tp-knowledge" aria-labelledby="knowledge-heading"><header><p className="tp-knowledge-eyebrow">BİLGİ REHBERİ</p><h1 id="knowledge-heading">Türkçe bilgi kütüphanesi</h1><p>Tarla, bitki, toprak, sulama ve tarım teknolojilerini anlaşılır Türkçe ile keşfet.</p></header><div className="tp-knowledge-filters"><label className="tp-knowledge-search">Bilgi ara<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Örn. azot, NDVI, sulama, pH…"/></label><label>Konu<select value={category} onChange={e=>setCategory(e.target.value)}><option>Tümü</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label></div><p role="status" className="tp-knowledge-count">{articles.length} rehber konusu</p>{selected?<article className="tp-knowledge-detail"><button type="button" onClick={()=>setSelectedId(null)}>‹ Bilgi Kütüphanesine Dön</button><small>{selected.category}</small><h2>{selected.title}</h2><p>{selected.summary}</p>{selected.sections.map(s=><section key={s.title}><h3>{s.title}</h3><p>{s.text}</p></section>)}<aside><p>Bu içerik eğitim ve genel bilgilendirme amaçlıdır. Tarla uygulamalarında analiz sonuçları, yerel koşullar, yürürlükteki resmî bilgiler ve gerektiğinde yetkili uzman değerlendirmesi esas alınmalıdır.</p></aside></article>:<div className="tp-knowledge-grid">{articles.map(a=><article key={a.id}><span className="tp-knowledge-badge">{a.category} · Rehber</span><h2>{a.title}</h2><p>{a.summary}</p><button type="button" onClick={()=>setSelectedId(a.id)}>Bilgiyi aç</button></article>)}</div>}{!selected&&<details className="tp-knowledge-sources"><summary>Hastalık sözlüğü ({labels.length})</summary><p>PlantVillage sınıf adları yalnızca arama ve sınıflandırma sözlüğüdür; teşhis veya mücadele reçetesi değildir.</p>{labels.map(e=><article key={e.id}><h2>{e.titleTr}</h2><p>{e.crops.join(' · ')}</p><p>{e.summaryTr}</p></article>)}</details>}{!selected&&<details className="tp-knowledge-sources"><summary>Kaynaklar ve lisans bilgisi</summary>{knowledgeSources.map(s=><article key={s.id}><h2>{s.name}</h2><p>{s.description}</p><small>{s.license} · Kaynak kontrolü: {s.checkedAt}</small></article>)}</details>}</section>;
}
