export type KnowledgeGuideExtraArticle = { id:string; category:string; title:string; summary:string; tags:string[]; sections:Array<{title:string;text:string}> };
export const KNOWLEDGE_GUIDE_EXTRA_ARTICLES: KnowledgeGuideExtraArticle[] = [
{id:'wheat-guide',category:'Bitkisel Üretim',title:'Buğdayda Temel Tarla Takibi',summary:'Çıkıştan hasada gelişim dönemlerini ve tarla farklılıklarını izleme.',tags:['buğday','tahıl','fenoloji'],sections:[{title:'Sezon boyunca izleme',text:'Çıkış, kardeşlenme, sap uzaması, başaklanma, çiçeklenme ve tane dolumu dönemleri ayrı kaydedilmelidir. Su ve besin ihtiyacı ile hastalık riski gelişim dönemine göre değişebilir.'}]},
{id:'corn-guide',category:'Bitkisel Üretim',title:'Mısırda Gelişim Dönemlerini Takip Etme',summary:'Vejetatif ve generatif dönemleri izleyerek saha kayıtlarını anlamlandırma.',tags:['mısır','fenoloji','sulama'],sections:[{title:'Dönem neden önemli?',text:'Yaprak gelişimi, püskül çıkarma, koçan püskülü ve tane dolumu gibi dönemler su stresi ve besleme değerlendirmelerinde önemli bağlam sağlar.'}]},
{id:'sunflower-guide',category:'Bitkisel Üretim',title:'Ayçiçeğinde Tarla Takibi',summary:'Çıkış, tabla oluşumu, çiçeklenme ve tane dolumu dönemlerinde temel saha gözlemleri.',tags:['ayçiçeği','fenoloji'],sections:[{title:'Düzenli gözlem',text:'Bitki sıklığı, gelişim homojenliği, yaprak belirtileri, yabancı ot baskısı ve çiçeklenme durumu tarlanın farklı bölgelerinde düzenli kaydedilmelidir.'}]},
{id:'salinity',category:'Toprak',title:'Toprak Tuzluluğu Nedir?',summary:'Çözünmüş tuzların bitki su alımı ve gelişimi üzerindeki etkisine giriş.',tags:['tuzluluk','EC','toprak'],sections:[{title:'Ölçüm önemlidir',text:'Tuzluluk bitkinin su almasını zorlaştırabilir. Kesin değerlendirme için uygun toprak veya sulama suyu analizindeki elektriksel iletkenlik gibi ölçümler kullanılmalıdır.'}]},
{id:'compaction',category:'Toprak',title:'Toprak Sıkışması ve Kök Gelişimi',summary:'Sıkışmış tabakaların köklenme, su hareketi ve havalanma üzerindeki olası etkileri.',tags:['sıkışma','kök','toprak'],sections:[{title:'Saha işaretleri',text:'Köklerin belirli derinlikte yön değiştirmesi, suyun yüzeyde kalması ve teker izlerinde gelişim farkları sıkışma şüphesi oluşturabilir. Tek belirti kesin teşhis değildir.'}]},
{id:'cec',category:'Toprak',title:'Katyon Değişim Kapasitesi (KDK/CEC)',summary:'Toprağın pozitif yüklü besin iyonlarını tutma kapasitesini ifade eden özellik.',tags:['KDK','CEC','toprak analizi'],sections:[{title:'Yorum',text:'KDK; kil mineralleri, organik madde ve pH gibi özelliklerle ilişkilidir. Laboratuvar sonucu diğer toprak analizleriyle birlikte yorumlanmalıdır.'}]},
{id:'calcium',category:'Bitki Besleme',title:'Kalsiyumun Bitkideki Rolü',summary:'Hücre duvarı ve genç dokuların gelişiminde kalsiyumun temel işlevleri.',tags:['kalsiyum','Ca','besleme'],sections:[{title:'Görevi',text:'Kalsiyum hücre duvarı ve zar yapısında rol oynar. Görsel belirti tek başına eksiklik teşhisi için yeterli değildir.'}]},
{id:'magnesium',category:'Bitki Besleme',title:'Magnezyum ve Klorofil',summary:'Magnezyumun klorofil ve enzim faaliyetlerindeki rolü.',tags:['magnezyum','Mg','klorofil'],sections:[{title:'Görevi',text:'Magnezyum klorofil molekülünün merkezinde yer alır ve birçok enzimatik süreçte görev yapar. Eksiklik şüphesi uygun analizle doğrulanmalıdır.'}]},
{id:'sulfur',category:'Bitki Besleme',title:'Kükürtün Bitki Beslemedeki Rolü',summary:'Protein oluşumu ve metabolik süreçlerde kükürdün önemini anlamak.',tags:['kükürt','S','besleme'],sections:[{title:'Görevi',text:'Kükürt bazı amino asitlerin ve proteinlerin yapısına katılır. Belirtiler başka beslenme sorunlarıyla karışabileceğinden analizle birlikte değerlendirilmelidir.'}]},
{id:'waterlogging',category:'Sulama',title:'Aşırı Sulama ve Su Birikmesi',summary:'Kök bölgesinde fazla suyun havalanma ve bitki gelişimi üzerindeki etkileri.',tags:['aşırı sulama','drenaj','kök'],sections:[{title:'Neden risklidir?',text:'Uzun süre doygun kalan kök bölgesinde oksijen azalabilir; kök işlevi ve besin alımı etkilenebilir. Sulama kararı yalnızca yüzey görünümüne göre verilmemelidir.'}]},
{id:'irrigation-water',category:'Sulama',title:'Sulama Suyu Kalitesi Neden Önemlidir?',summary:'Su kalite özelliklerinin uzun dönemli toprak ve bitki yönetimine etkisi.',tags:['su analizi','tuzluluk','sulama'],sections:[{title:'Analiz',text:'Sulama suyunun tuzluluk ve ilgili kimyasal özellikleri zamanla ürün ve toprağı etkileyebilir. Risk değerlendirmesinde laboratuvar su analizi ve yerel koşullar birlikte kullanılmalıdır.'}]},
{id:'rotation',category:'Tarla İşlemleri',title:'Ekim Nöbeti (Münavebe) Nedir?',summary:'Aynı tarlada ürünleri planlı sırayla değiştirmenin üretim yönetimindeki yeri.',tags:['münavebe','ekim nöbeti'],sections:[{title:'Neden yapılır?',text:'Uygun ürün rotasyonu bazı hastalık, zararlı ve yabancı ot döngülerinin yönetimine, toprak yapısının korunmasına ve üretim riskinin dağıtılmasına katkı sağlayabilir.'}]},
{id:'weed-scouting',category:'Hastalık ve Zararlılar',title:'Yabancı Otları Erken Dönemde Tanıma',summary:'Yabancı ot türü ve yoğunluğunu uygulama kararından önce kaydetme yaklaşımı.',tags:['yabancı ot','gözlem'],sections:[{title:'Önce tanı',text:'Yabancı otun türü, gelişim dönemi ve tarladaki dağılımı kaydedilmelidir. Mücadele yöntemi seçilirken kültür bitkisi ve yürürlükteki ürün etiketi dikkate alınmalıdır.'}]},
{id:'fungal-risk',category:'Hastalık ve Zararlılar',title:'Hastalık Riskinde Nem ve Yaprak Islaklığı',summary:'Nemli koşulların bazı bitki hastalıklarının gelişim riskini neden artırabildiğini anlamak.',tags:['hastalık riski','nem','yaprak ıslaklığı'],sections:[{title:'Risk teşhis değildir',text:'Uzun süreli yaprak ıslaklığı, uygun sıcaklık ve yüksek nem bazı hastalıklar için elverişli koşullar oluşturabilir. Hava koşulu risk göstergesidir; teşhis saha belirtisi ve gerektiğinde laboratuvar doğrulaması gerektirir.'}]},
{id:'lst',category:'Uydu ve Tarım Teknolojisi',title:'LST: Arazi Yüzey Sıcaklığı Nedir?',summary:'Uydu verisinden tahmin edilen yüzey sıcaklığının tarla gözlemindeki yerini anlamak.',tags:['LST','yüzey sıcaklığı','uydu'],sections:[{title:'Hava sıcaklığı değildir',text:'LST arazi yüzeyinin radyometrik sıcaklığına ilişkin uzaktan algılama ürünüdür; meteoroloji istasyonundaki hava sıcaklığıyla aynı değişken değildir.'}]},
{id:'gndvi',category:'Uydu ve Tarım Teknolojisi',title:'GNDVI Nedir?',summary:'Yeşil bant ve yakın kızılötesi verilerinden hesaplanan vejetasyon indeksine giriş.',tags:['GNDVI','uydu','vejetasyon'],sections:[{title:'Yorum',text:'GNDVI bitki örtüsündeki spektral değişimleri izlemek için kullanılabilir. Değer değişimi doğrudan tek bir besin elementi veya hastalık teşhisi olarak yorumlanmamalıdır.'}]},
{id:'cloud-mask',category:'Uydu ve Tarım Teknolojisi',title:'Bulut ve Gölge Uydu Analizini Nasıl Etkiler?',summary:'Optik uydu görüntülerinde veri kalitesinin neden kontrol edilmesi gerektiği.',tags:['bulut','Sentinel-2','veri kalitesi'],sections:[{title:'Kalite kontrolü',text:'Bulut ve bulut gölgeleri yüzey sinyalini örterek vejetasyon indekslerini bozabilir. Sahne tarihi, bulut bilgisi ve kalite maskeleri analizden önce kontrol edilmelidir.'}]},
{id:'satellite-date',category:'Uydu ve Tarım Teknolojisi',title:'Uydu Verisinin Tarihi Neden Önemlidir?',summary:'Harita altlığının görüntü tarihi ile analiz sensörünün veri tarihini birbirinden ayır.',tags:['veri tarihi','uydu','harita'],sections:[{title:'İki farklı tarih olabilir',text:'Haritada görünen taban fotoğrafı ile NDVI gibi bir katmanın hesaplandığı sensör sahnesi aynı tarihe ait olmak zorunda değildir. Tarımsal yorumda analiz katmanının gerçek veri tarihi gösterilmelidir.'}]},
{id:'degree-day',category:'Tarım Sözlüğü',title:'Büyüme Derece-Gün Kavramı',summary:'Sıcaklık birikimini bitki veya zararlı gelişimiyle ilişkilendiren kavrama giriş.',tags:['derece-gün','sıcaklık','fenoloji'],sections:[{title:'Kavram',text:'Derece-gün, belirli bir taban sıcaklığın üzerindeki ısı birikimini zaman içinde ifade eden yaklaşımdır. Taban sıcaklık ve hesaplama yöntemi hedefe göre değişebilir.'}]},
{id:'field-capacity',category:'Tarım Sözlüğü',title:'Tarla Kapasitesi ve Solma Noktası',summary:'Toprağın bitkiye kullanılabilir su sağlamasını anlamak için iki temel kavram.',tags:['tarla kapasitesi','solma noktası','su'],sections:[{title:'Kullanılabilir su',text:'Tarla kapasitesi drenaj sonrası toprakta tutulan su durumunu, kalıcı solma noktası ise bitkinin suyu almakta çok zorlandığı alt sınırı ifade eden kavramlardır.'}]}
];
