export type SoilHealthGuideArticle={id:string;category:string;title:string;summary:string;tags:string[];sections:Array<{title:string;text:string}>};

export const KNOWLEDGE_GUIDE_SOIL_HEALTH_ARTICLES:SoilHealthGuideArticle[]=[
{id:'soil-health-concept',category:'Toprak',title:'Toprak Sağlığı Nedir?',summary:'Toprağın fiziksel, kimyasal ve biyolojik işlevlerini birlikte değerlendiren yaklaşım.',tags:['toprak sağlığı','biyoloji','yapı'],sections:[{title:'Tek ölçüm değildir',text:'Toprak sağlığı tek bir rakamla açıklanamaz. Su düzenleme, besin döngüsü, bitki gelişimini destekleme ve biyolojik yaşam gibi işlevler; fiziksel, kimyasal ve biyolojik göstergeler birlikte değerlendirilerek izlenir.'},{title:'Zaman içinde izleme',text:'Göstergeler aynı tarlada farklı tarihlerde veya benzer yönetilen alanlarla karşılaştırıldığında daha anlamlı hale gelir. Verim tek başına toprak sağlığını göstermez.'}]},
{id:'living-root',category:'Toprak',title:'Canlı Kök Neden Önemlidir?',summary:'Kök bölgesindeki biyolojik faaliyetin toprak işlevleriyle ilişkisi.',tags:['canlı kök','rizosfer','mikroorganizma'],sections:[{title:'Rizosfer',text:'Canlı köklerin çevresindeki rizosfer, yoğun biyolojik faaliyetin gerçekleştiği bölgedir. Köklerden salınan bileşikler mikroorganizmalar için enerji kaynağı sağlayabilir ve besin döngüsüne katkıda bulunabilir.'}]},
{id:'soil-cover-benefits',category:'Toprak',title:'Toprağı Örtülü Tutmanın Faydaları',summary:'Bitki artığı ve canlı örtünün erozyon, nem ve yüzey sıcaklığı üzerindeki rolü.',tags:['toprak örtüsü','anız','erozyon'],sections:[{title:'Yüzeyi korumak',text:'Toprak yüzeyindeki bitki artıkları veya canlı örtü yağmur damlalarının doğrudan etkisini azaltabilir, yüzey akışını ve erozyon riskini sınırlamaya yardımcı olabilir.'},{title:'Su ve sıcaklık',text:'Örtü, yüzeyden su kaybını azaltmaya ve toprak sıcaklığındaki aşırı değişimleri sınırlamaya yardımcı olabilir. Etki; örtü miktarı, iklim ve toprak koşullarına göre değişir.'}]},
{id:'minimum-disturbance',category:'Tarla İşlemleri',title:'Toprak İşlemeyi Azaltmak Ne Anlama Gelir?',summary:'Gereksiz mekanik bozulmayı azaltmanın toprak yapısıyla ilişkisi.',tags:['azaltılmış işleme','doğrudan ekim','toprak yapısı'],sections:[{title:'Amaç',text:'Toprak işlemenin azaltılması, uygun sistemlerde toprağın fiziksel yapısının ve biyolojik habitatın gereksiz yere bozulmasını sınırlamayı amaçlar. Uygulama biçimi ürün, toprak, iklim ve ekipmana göre planlanmalıdır.'},{title:'Tek başına çözüm değildir',text:'Azaltılmış işleme; ürün çeşitliliği, yüzey örtüsü, yabancı ot yönetimi ve uygun ekim sistemiyle birlikte ele alındığında daha anlamlıdır.'}]},
{id:'crop-diversity-soil',category:'Bitkisel Üretim',title:'Ürün Çeşitliliği Toprağı Nasıl Etkiler?',summary:'Farklı kök yapıları ve ürün dizilerinin toprak ekosistemine katkısı.',tags:['münavebe','ürün çeşitliliği','kök'],sections:[{title:'Farklı kökler, farklı etkiler',text:'Farklı bitki türleri değişik kök derinlikleri ve kök salgılarıyla toprak profilinin farklı bölümlerini kullanabilir. Çeşitli ürün dizileri toprak biyolojik çeşitliliğini destekleyebilir.'},{title:'Hastalık ve zararlı döngüsü',text:'Uygun münavebe, yalnızca belirli bir üründe çoğalan bazı hastalık ve zararlıların ardışık sezonlarda taşınma riskini azaltmaya yardımcı olabilir; sonuç organizmaya ve bölgeye göre değişir.'}]},
{id:'cover-crop-purpose',category:'Bitkisel Üretim',title:'Örtü Bitkisi Neden Yetiştirilir?',summary:'Ana ürünler arasındaki dönemde toprağı korumak ve sistemi desteklemek için kullanılan bitkiler.',tags:['örtü bitkisi','münavebe','toprak'],sections:[{title:'Amaçlar',text:'Örtü bitkileri çıplak dönemlerde toprağı korumak, erozyon riskini azaltmak, yaşayan kök süresini uzatmak, besin döngüsünü desteklemek ve bazı sistemlerde yabancı ot baskısını artırmak için kullanılabilir.'},{title:'Seçim yereldir',text:'Tür ve karışım seçimi; iklim, su durumu, ana ürün, ekim-hasat takvimi, toprak sorunu ve işletme amacına göre yapılmalıdır. Her örtü bitkisi her tarla için uygun değildir.'}]},
{id:'residue-management',category:'Tarla İşlemleri',title:'Hasat Artıklarını Yönetmek',summary:'Sap ve diğer bitki artıklarının toprak yüzeyindeki işlevlerini anlamak.',tags:['anız','bitki artığı','organik madde'],sections:[{title:'Artıkların rolü',text:'Hasat artıkları yüzeyi örterek erozyona karşı fiziksel koruma sağlayabilir ve ayrıştıkça karbon ile besin döngüsüne katkıda bulunabilir.'},{title:'Denge gerekir',text:'Artık yönetimi sonraki ürünün ekimi, hastalık ve zararlı geçmişi, yangın riski, hayvancılık kullanımı ve ayrışma koşullarıyla birlikte planlanmalıdır.'}]},
{id:'aggregate-stability',category:'Toprak',title:'Toprak Agregat Dayanıklılığı Nedir?',summary:'Toprak parçacıklarının kümeler halinde dayanıklılığının su hareketi ve erozyonla ilişkisi.',tags:['agregat','toprak yapısı','infiltrasyon'],sections:[{title:'Neden izlenir?',text:'Dayanıklı agregatlar gözenek yapısının korunmasına, suyun toprağa girişine ve yüzey kabuklaşmasının sınırlanmasına yardımcı olabilir. Agregat yapısı organik madde, kökler, biyolojik faaliyet ve yönetimden etkilenir.'}]},
{id:'soil-health-indicators',category:'Toprak',title:'Toprak Sağlığı Göstergeleri',summary:'Fiziksel, kimyasal ve biyolojik göstergeleri birlikte okuma yaklaşımı.',tags:['gösterge','analiz','izleme'],sections:[{title:'Üç boyut',text:'Toprak bünyesi, sıkışma ve su hareketi gibi fiziksel; pH, tuzluluk ve besin durumu gibi kimyasal; organik madde ve biyolojik faaliyetle ilişkili biyolojik göstergeler birlikte değerlendirilir.'},{title:'Bağlam önemlidir',text:'Bir göstergenin iyi veya kötü kabul edilmesi toprak tipi, iklim, ürün ve ölçüm yöntemine bağlı olabilir. Bu nedenle tek bir evrensel eşik yerine yerel karşılaştırma ve zaman serisi değerlidir.'}]},
{id:'nutrient-4r',category:'Bitki Besleme',title:'Besin Yönetiminde 4 Doğru İlkesi',summary:'Doğru kaynak, miktar, zaman ve uygulama yerini birlikte düşünme yaklaşımı.',tags:['4D','besin yönetimi','gübreleme'],sections:[{title:'Dört karar',text:'Besin yönetiminde doğru kaynak, doğru miktar, doğru zaman ve doğru yer birlikte düşünülür. Amaç ürün ihtiyacını karşılarken besin kayıplarını ve çevresel etkileri azaltmaktır.'},{title:'Miktar reçetesi değildir',text:'Bu rehber sabit gübre dozu vermez. Miktar ve ürün seçimi; toprak ve gerektiğinde bitki analizi, ürün hedefi, gelişim dönemi, önceki uygulamalar ve yerel koşullara göre belirlenmelidir.'}]},
{id:'nutrient-loss-pathways',category:'Bitki Besleme',title:'Besinler Tarladan Nasıl Kaybolabilir?',summary:'Yıkanma, yüzey akışı, erozyon ve gaz kayıplarını kavramsal olarak tanıma.',tags:['besin kaybı','yıkanma','yüzey akışı'],sections:[{title:'Kayıp yolları',text:'Besinler toprak ve koşullara bağlı olarak kök bölgesinin altına yıkanma, yüzey akışı ve erozyonla taşınma veya bazı azot formlarında gaz halinde kayıp yollarıyla sistemden uzaklaşabilir.'},{title:'Yönetim',text:'Kaybı azaltmak için besin kaynağı, miktarı, uygulama zamanı ve yeri; yağış, sulama, toprak özellikleri ve bitkinin alım dönemiyle birlikte değerlendirilmelidir.'}]},
{id:'infiltration-management',category:'Sulama',title:'Su İnfiltrasyonunu Yönetim Nasıl Etkiler?',summary:'Toprak yapısı, örtü ve sıkışmanın suyun toprağa girişindeki rolü.',tags:['infiltrasyon','su','sıkışma'],sections:[{title:'Suyun toprağa girişi',text:'İnfiltrasyon; toprak bünyesi yanında gözenek yapısı, yüzey kabuklaşması, sıkışma, organik madde ve yüzey örtüsünden etkilenebilir. Sağanak sırasında suyun toprağa giriş hızının aşılması yüzey akışını artırabilir.'}]},
{id:'runoff-erosion-link',category:'Toprak',title:'Yüzey Akışı ve Erozyon İlişkisi',summary:'Toprağa giremeyen suyun toprak parçacıklarını taşıma riskini anlamak.',tags:['yüzey akışı','erozyon','yağış'],sections:[{title:'Temel ilişki',text:'Yağış veya sulama suyu toprağa yeterince hızlı giremediğinde yüzey akışı oluşabilir. Eğim, çıplak yüzey ve zayıf yapı koşullarında bu akış toprak parçacıklarının taşınmasını artırabilir.'}]},
{id:'field-traffic-soil-health',category:'Tarla İşlemleri',title:'Tarla Trafiği ve Toprak Sağlığı',summary:'Ağır ekipman geçişlerinin özellikle ıslak topraktaki sıkışma riskini anlamak.',tags:['tarla trafiği','sıkışma','makine'],sections:[{title:'Risk',text:'Toprak taşıma kapasitesinin düşük olduğu ıslak koşullarda ağır makine trafiği gözenek hacmini azaltabilir ve sıkışmayı artırabilir. Etki ekipman yükü, lastik-basınç düzeni, geçiş sayısı ve toprak nemine bağlıdır.'},{title:'Kayıt tutmak',text:'Geçiş tarihleri, toprak durumu ve sorunlu alanların kaydı sonraki sezonlarda aynı bölgelerdeki yapısal sorunları karşılaştırmaya yardımcı olur.'}]},
{id:'soil-carbon-vs-organic-matter',category:'Tarım Sözlüğü',title:'Toprak Organik Karbonu ve Organik Madde Aynı Şey mi?',summary:'Birbiriyle ilişkili iki kavram arasındaki temel fark.',tags:['organik karbon','organik madde','karbon'],sections:[{title:'Kavram farkı',text:'Toprak organik karbonu, topraktaki organik bileşiklerin karbon kısmını ifade eder. Organik madde ise karbonun yanında başka elementleri de içeren daha geniş organik materyal havuzudur. Laboratuvar yöntemine göre raporlama biçimi değişebilir.'}]},
{id:'soil-food-web',category:'Tarım Sözlüğü',title:'Toprak Besin Ağı Nedir?',summary:'Topraktaki canlıların organik materyal ve besin döngüsü çevresindeki ilişkileri.',tags:['toprak biyolojisi','mikroorganizma','besin ağı'],sections:[{title:'Canlı sistem',text:'Bakteriler, mantarlar, protozoalar, nematodlar, eklembacaklılar ve diğer canlılar organik materyalin parçalanması ve besin döngüsü içinde birbirleriyle etkileşir. Bu topluluğun yapısı toprak, iklim ve yönetim koşullarına göre değişir.'}]}
];
